version: "3"

silent: true

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  run-dev:
    aliases:
      - rd
    desc: Run the application in development mode
    cmd: docker compose up -d && go run main.go

  run-down:
    aliases:
      - rd
    desc: Run the application in development mode
    cmd: docker compose down
