apiVersion: 1

datasources:

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
      - datasourceUid: Tempo
        matcherRegex: "traceID=(\\w+)"
        name: TraceID
        url: 'http://tempo:3200/trace/$${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      timeout: 60
      maxLines: 1000
      tracesToLogsV2:
        datasourceUid: 'Loki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [
            { key: 'main-api'}
        ]
        filterByTraceID: true
        filterBySpanID: true
        customQuery: false